// <auto-generated />
namespace TaskManager.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EmployeeIDDataTypeChangedInTaskTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmployeeIDDataTypeChangedInTaskTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202207040827512_EmployeeID-DataType-ChangedIn-TaskTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
