// <auto-generated />
namespace TaskManager.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removedstatuscolumninDepartment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedstatuscolumninDepartment));
        
        string IMigrationMetadata.Id
        {
            get { return "202206280624547_removed-status-column-inDepartment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
